### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JordanSussman** [aidansteele/rdsconn#3]
Thanks for taking the time to build this! Any chance I could convince you to add a license to make consumptions/contributions easier? The [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) talks a lot about selecting a license and some of the ramifications of a project not having one.

**Comment by aidansteele** [comment]
Doh! Thank you for the reminder, can't believe I forgot this. I've added an MIT licence, so I'll close this now. Thanks!
